package com.example.backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import jakarta.persistence.*;
import java.math.BigDecimal;
import java.time.LocalDate;

@Entity
@Getter
@Setter
public class AccountStatement {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "accountNumber", nullable = false)
    private Account account;

    private LocalDate statementDate;
    private BigDecimal openingBalance;
    private BigDecimal closingBalance;

    // Default constructor, getters, and setters are generated by Lombok
}
