package com.example.backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
public class AuditLog {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    private String eventType;
    private LocalDateTime eventTimestamp;
    private String accountNumber;
    private String description;

    @ManyToOne
    @JoinColumn(name = "adminId", nullable = true)
    private User admin;

    // Default constructor, getters, and setters are generated by Lombok
}
