package com.example.backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

import java.time.LocalDateTime;

@Entity
@Getter
@Setter
public class BeneficiaryApproval {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "beneficiaryId", nullable = false)
    private Beneficiary beneficiary;

    @ManyToOne
    @JoinColumn(name = "adminId", nullable = false)
    private User admin;

    private String approvalStatus;
    private LocalDateTime approvalDate;

    // Default constructor, getters, and setters are generated by Lombok
}
