package com.example.backend.entity;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;

@Entity
@Getter
@Setter
public class Beneficiary {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @ManyToOne
    @JoinColumn(name = "accountNumber", nullable = false)
    private Account account;

    private String beneficiaryName;
    private String beneficiaryAccountNumber;

    // Default constructor, getters, and setters are generated by Lombok
}
